version: 0.2

# based on:
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html

# CodeBuilt environment variables:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

phases:
  pre_build:
    commands:
      - echo `date` Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - REVISION=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo `date` Building the Docker image $IMAGE_NAME:$REVISION...
      - docker build -t $IMAGE_NAME:$REVISION -f server/ci/Dockerfile server/.
  post_build:
    commands:
      - REGISTRY_IMAGE_URI = $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$REVISION
      - docker tag $IMAGE_NAME:$REVISION $REGISTRY_IMAGE_URI
      - echo `date` pushing image to $REGISTRY_IMAGE_URI
      - docker push $REGISTRY_IMAGE_URI
